language: generic

sudo: false

cache:
  directories:
  - $HOME/.ghc
  - $HOME/.cabal
  - $HOME/.stack

matrix:
  include:
  - env: BUILD=cabal
    addons: {apt: {packages: [cabal-install-1.24,ghc-8.0.2], sources: [hvr-ghc]}}
  - env: BUILD=stack
  - env: BUILD=stackage
  - env: BUILD=hlint
  - env: BUILD=stylish-haskell
  - env: BUILD=sdist
  - env: BUILD=readme

before_install:
- unset CC
- case "$BUILD" in
    cabal)
      export PATH=$HOME/.cabal/bin:/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
      ;;
    *)
      export PATH=$HOME/.local/bin:/opt/ghc/$GHCVER/bin:$PATH;
      ;;
  esac

install:
- |
  set -ex
  case "$BUILD" in
    cabal)
      travis_retry cabal update -v
      cabal install alex happy  # FIXME: https://github.com/yav/pretty-show/issues/24
      cabal install --only-dependencies --enable-tests
      ;;
    *)
      mkdir -p ~/.local/bin;
      travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
      stack install --pedantic
      ;;
  esac
  set +ex

script:
- |
  set -ex
  case "$BUILD" in
    cabal)
      cabal configure --enable-tests
      cabal install
      cabal test
      ;;
    stack)
      make test
      ;;
    stackage)
      stack build --resolver nightly --haddock --test --bench --no-run-benchmarks
      ;;
    hlint)
      make hlint_binary
      ;;
    stylish-haskell)
      make stylish_haskell
      ;;
    sdist)
      make test_sdist
      ;;
    readme)
      make test_readme
  esac
  set +ex

notifications:
  email: false
