sudo: required

language: haskell

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.stack/

env:
- TEST_DIR=$TRAVIS_BUILD_DIR/tasty-discover-example

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
- stack --no-terminal setup

script:
- cd $TEST_DIR
- stack --no-terminal test
- echo .stack-work/logs/*-test.log
